"""Deterministic experiment code generation.

Produces complete, runnable ``experiment.py`` source from an
``ExperimentDesign``. Two roles:

1. The Engineer's fallback when no LLM is configured (or when the LLM's own
   code fails twice), so the loop always has runnable code.
2. The worked example embedded in the Engineer's prompt, which is what keeps
   LLM-authored code conforming to the result.json contract.

Metrics are always computed by this code at run time from real predictions --
nothing here fabricates a number.
"""
from __future__ import annotations

from typing import Any

from .schemas import ExperimentDesign

# Only these kwargs are forwarded to each estimator. An LLM inventing
# `learning_rate` for IsolationForest would otherwise crash the run.
_ALLOWED_PARAMS: dict[str, set[str]] = {
    "isolation_forest": {"n_estimators", "max_samples", "contamination", "max_features", "bootstrap"},
    "one_class_svm": {"nu", "kernel", "gamma", "degree", "coef0", "tol"},
    "random_forest": {"n_estimators", "max_depth", "min_samples_split", "min_samples_leaf", "max_features", "class_weight", "criterion"},
    "gradient_boosting": {"max_iter", "learning_rate", "max_depth", "min_samples_leaf", "l2_regularization"},
    "autoencoder": {"hidden_layer_sizes", "alpha", "max_iter", "learning_rate_init"},
    "ensemble_adaptive": {"n_estimators", "contamination", "max_depth", "class_weight"},
}

_DEFAULTS: dict[str, dict[str, Any]] = {
    "isolation_forest": {"n_estimators": 200, "contamination": 0.09},
    "one_class_svm": {"nu": 0.09, "kernel": "rbf", "gamma": "scale"},
    "random_forest": {"n_estimators": 200, "class_weight": "balanced"},
    "gradient_boosting": {"max_iter": 200, "learning_rate": 0.1},
    "autoencoder": {"hidden_layer_sizes": 6, "alpha": 1e-4, "max_iter": 300},
    "ensemble_adaptive": {"n_estimators": 200, "contamination": 0.09},
}


def _params_for(design: ExperimentDesign) -> dict[str, Any]:
    allowed = _ALLOWED_PARAMS.get(design.approach, set())
    merged = dict(_DEFAULTS.get(design.approach, {}))
    for key, value in (design.parameters or {}).items():
        if key in allowed:
            merged[key] = value
    return merged


_PREAMBLE = '''"""GENESIS experiment: {name}

Hypothesis approach : {approach}
Feature set         : {feature_set}
Threshold strategy  : {threshold_strategy}

Generated by the ENGINEER agent. Executed in an isolated sandbox with no
network access. Metrics below are computed from real predictions.
"""
import json
import time

import numpy as np
from genesis_data import load_dataset
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_recall_fscore_support,
    roc_auc_score,
)

RANDOM_STATE = 42
start = time.time()

X_train, X_test, y_train, y_test, feature_names = load_dataset(
    feature_set="{feature_set}", seed=RANDOM_STATE
)
print(f"dataset: train={{X_train.shape}} test={{X_test.shape}} features={{len(feature_names)}}")
print(f"train anomaly rate={{y_train.mean():.4f}}  test anomaly rate={{y_test.mean():.4f}}")

scaler = StandardScaler().fit(X_train)
Xtr = scaler.transform(X_train)
Xte = scaler.transform(X_test)
'''

_MODELS: dict[str, str] = {
    "isolation_forest": '''
from sklearn.ensemble import IsolationForest

model = IsolationForest(random_state=RANDOM_STATE, {params})
model.fit(Xtr)
# Higher score == more anomalous.
train_scores = -model.score_samples(Xtr)
test_scores = -model.score_samples(Xte)
supervised = False
''',
    "one_class_svm": '''
from sklearn.linear_model import SGDOneClassSVM
from sklearn.kernel_approximation import Nystroem
from sklearn.pipeline import make_pipeline

# Nystroem + SGD keeps this near-linear; a plain OneClassSVM is O(n^2) and
# would routinely exceed the sandbox timeout on this dataset.
_nu = {nu}
model = make_pipeline(
    Nystroem(n_components=256, random_state=RANDOM_STATE),
    SGDOneClassSVM(nu=_nu, random_state=RANDOM_STATE, max_iter=2000, tol=1e-4),
)
model.fit(Xtr)
train_scores = -model.decision_function(Xtr)
test_scores = -model.decision_function(Xte)
supervised = False
''',
    "random_forest": '''
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=RANDOM_STATE, n_jobs=1, {params})
model.fit(Xtr, y_train)
train_scores = model.predict_proba(Xtr)[:, 1]
test_scores = model.predict_proba(Xte)[:, 1]
supervised = True
''',
    "gradient_boosting": '''
from sklearn.ensemble import HistGradientBoostingClassifier

model = HistGradientBoostingClassifier(random_state=RANDOM_STATE, {params})
model.fit(Xtr, y_train)
train_scores = model.predict_proba(Xtr)[:, 1]
test_scores = model.predict_proba(Xte)[:, 1]
supervised = True
''',
    "autoencoder": '''
from sklearn.neural_network import MLPRegressor

# Reconstruction-error autoencoder trained on NORMAL traffic only, so the
# reconstruction error itself becomes the anomaly score.
normal_only = Xtr[y_train == 0]
model = MLPRegressor(
    hidden_layer_sizes=({bottleneck},),
    activation="tanh",
    solver="adam",
    random_state=RANDOM_STATE,
    early_stopping=True,
    {params}
)
model.fit(normal_only, normal_only)
train_scores = np.mean((Xtr - model.predict(Xtr)) ** 2, axis=1)
test_scores = np.mean((Xte - model.predict(Xte)) ** 2, axis=1)
supervised = False
''',
    "ensemble_adaptive": '''
from sklearn.ensemble import IsolationForest, RandomForestClassifier

# Blend an unsupervised density signal with a supervised classifier: the
# forest catches known attack shapes, the isolation score catches novelty.
iso = IsolationForest(random_state=RANDOM_STATE, {iso_params})
iso.fit(Xtr)
clf = RandomForestClassifier(random_state=RANDOM_STATE, n_jobs=1, {clf_params})
clf.fit(Xtr, y_train)

# Both splits are mapped through the SAME reference distribution (the training
# isolation scores). Ranking each split independently would make a threshold
# tuned on train mean something different on test.
_iso_reference = np.sort(-iso.score_samples(Xtr))

def _blend(X):
    iso_pct = np.searchsorted(_iso_reference, -iso.score_samples(X)) / len(_iso_reference)
    clf_prob = clf.predict_proba(X)[:, 1]
    return 0.35 * iso_pct + 0.65 * clf_prob

train_scores = _blend(Xtr)
test_scores = _blend(Xte)
supervised = True
''',
}

_THRESHOLD = {
    "default": '''
if supervised:
    threshold = 0.5 if test_scores.max() <= 1.0 else float(np.median(test_scores))
else:
    # Flag the top-k by score, where k matches the training anomaly prior.
    threshold = float(np.quantile(train_scores, 1.0 - max(y_train.mean(), 0.01)))
''',
    "adaptive_percentile": '''
# Adaptive thresholding: place the cut at the training anomaly prior, then
# nudge it to the nearest local density minimum so the boundary sits in a
# sparse region of the score distribution rather than mid-cluster.
prior = float(max(y_train.mean(), 0.01))
base = float(np.quantile(train_scores, 1.0 - prior))
lo = float(np.quantile(train_scores, 1.0 - min(prior * 2.5, 0.5)))
hi = float(np.quantile(train_scores, 1.0 - prior * 0.35))
candidates = np.linspace(lo, hi, 60)
hist, edges = np.histogram(train_scores, bins=80)
density = np.interp(candidates, (edges[:-1] + edges[1:]) / 2.0, hist)
threshold = float(candidates[int(np.argmin(density))])
print(f"adaptive threshold: base={{base:.4f}} chosen={{threshold:.4f}}")
''',
    "f1_optimized": '''
# Tune the threshold on TRAIN ONLY, then apply it unchanged to the held-out
# test split. Sweeping on test would leak the evaluation set and inflate F1.
candidates = np.quantile(train_scores, np.linspace(0.50, 0.999, 120))
best_threshold, best_f1 = float(candidates[0]), -1.0
for candidate in candidates:
    train_pred = (train_scores >= candidate).astype(int)
    _, _, cand_f1, _ = precision_recall_fscore_support(
        y_train, train_pred, average="binary", zero_division=0
    )
    if cand_f1 > best_f1:
        best_threshold, best_f1 = float(candidate), float(cand_f1)
threshold = best_threshold
print(f"threshold tuned on train: {{threshold:.4f}} (train F1={{best_f1:.4f}})")
''',
}

_EPILOGUE = '''
y_pred = (test_scores >= threshold).astype(int)

precision, recall, f1, _ = precision_recall_fscore_support(
    y_test, y_pred, average="binary", zero_division=0
)
tn, fp, fn, tp = confusion_matrix(y_test, y_pred, labels=[0, 1]).ravel()
false_positive_rate = float(fp) / float(fp + tn) if (fp + tn) else 0.0

try:
    roc_auc = float(roc_auc_score(y_test, test_scores))
except ValueError:
    roc_auc = 0.0

elapsed = time.time() - start
metrics = {
    "accuracy": float(accuracy_score(y_test, y_pred)),
    "precision": float(precision),
    "recall": float(recall),
    "f1": float(f1),
    "false_positive_rate": false_positive_rate,
    "roc_auc": roc_auc,
    "true_positives": float(tp),
    "false_positives": float(fp),
    "false_negatives": float(fn),
    "true_negatives": float(tn),
    "n_test": float(len(y_test)),
}

for key, value in metrics.items():
    print(f"{key}: {value:.4f}")

with open("result.json", "w") as handle:
    json.dump(
        {
            "status": "success",
            "metrics": metrics,
            "artifacts": [
                {
                    "name": "confusion_matrix",
                    "kind": "json",
                    "content": json.dumps(
                        {"tn": int(tn), "fp": int(fp), "fn": int(fn), "tp": int(tp)}
                    ),
                }
            ],
            "execution_time": elapsed,
        },
        handle,
    )
print(f"experiment finished in {elapsed:.2f}s")
'''


def _fmt_params(params: dict[str, Any], exclude: set[str] | None = None) -> str:
    exclude = exclude or set()
    parts = []
    for key, value in params.items():
        if key in exclude:
            continue
        parts.append(f"{key}={value!r}")
    return ", ".join(parts)


def generate_experiment_code(design: ExperimentDesign) -> str:
    """Build complete runnable experiment source for a design.

    Only the built-in anomaly-detection approaches can be templated. A
    ``custom`` / ``self_contained`` design is authored by the Engineer's LLM;
    if that is unavailable this falls back to the anomaly baseline purely so
    the loop is never left without runnable code.
    """
    approach = design.approach
    if approach not in _MODELS:
        approach = "isolation_forest"

    params = _params_for(design)
    body_template = _MODELS[approach]

    if approach == "one_class_svm":
        body = body_template.format(nu=float(params.get("nu", 0.09)))
    elif approach == "autoencoder":
        bottleneck = params.pop("hidden_layer_sizes", 6)
        if not isinstance(bottleneck, int):
            bottleneck = 6
        body = body_template.format(
            bottleneck=max(2, min(int(bottleneck), 32)),
            params=_fmt_params(params),
        )
    elif approach == "ensemble_adaptive":
        iso_keys = {"n_estimators", "contamination"}
        body = body_template.format(
            iso_params=_fmt_params({k: v for k, v in params.items() if k in iso_keys}),
            clf_params=_fmt_params(
                {k: v for k, v in params.items() if k in {"max_depth", "class_weight"}}
                or {"class_weight": "balanced"}
            ),
        )
    else:
        body = body_template.format(params=_fmt_params(params))

    preamble = _PREAMBLE.format(
        name=design.name,
        approach=design.approach,
        feature_set=design.feature_set,
        threshold_strategy=design.threshold_strategy,
    )
    threshold = _THRESHOLD.get(design.threshold_strategy, _THRESHOLD["default"])
    return preamble + body + threshold + _EPILOGUE


CODE_CONTRACT = """\
The experiment runs in a locked-down sandbox. It MUST obey this contract:

* Available imports: numpy, scipy, scikit-learn, and (in builtin_anomaly mode)
  the provided `genesis_data` module. NOTHING else. There is no network, so you
  cannot download data or install packages.

* DATA. Two modes, chosen by the design's `dataset_mode`:

  - builtin_anomaly: the research question concerns NETWORK ANOMALY DETECTION.
    Load the shipped dataset:
        from genesis_data import load_dataset
        X_train, X_test, y_train, y_test, feature_names = load_dataset(
            feature_set="base"|"temporal", seed=42)
    y arrays are ints (0 = normal, 1 = anomaly); the split is chronological.

  - self_contained: the question is about SOME OTHER domain. `genesis_data` is
    irrelevant -- do NOT import it. Generate a deterministic synthetic dataset
    inside the experiment with numpy (np.random.default_rng(42)) that genuinely
    embodies the phenomenon under test, then train and evaluate on it. State in
    a comment what the generative process is and why it is a fair test of the
    hypothesis. Never construct data whose answer is baked in.

    THE SETUP MUST BE NON-DEGENERATE. Before measuring, assert that the problem
    instance actually admits a meaningful answer, and regenerate with easier
    parameters until it does. A run that reports "no path found", an empty
    class, zero variance, or a sentinel like -1 has measured nothing and is a
    FAILED experiment, not a result. Examples of the check you must make:
      * pathfinding / search : a route from start to goal exists
      * classification       : both classes present in train AND test
      * regression           : the target has non-zero variance
      * clustering           : more samples than requested clusters
    Bound the retry loop (say 20 attempts) and raise if it cannot be satisfied,
    so the Engineer sees a real error instead of a null result.

* RESULTS. Write `result.json` in the working directory:
      {"status": "success",
       "metrics": {"<name>": <number>, ...},
       "artifacts": [], "execution_time": <seconds>}
  Report metrics appropriate to the task (classification: accuracy/precision/
  recall/f1; regression: rmse/mae/r2; ranking: ndcg/map, and so on).
  ALSO declare which metric the lab should rank by, and in which direction:
      "primary_metric": "f1",            # a key that exists in "metrics"
      "metric_direction": "maximize"     # or "minimize" (e.g. rmse, runtime)
  For classification, name it `f1`. Keep the same primary metric across every
  experiment in a run so results stay comparable.
  Every metric must be a real number computed from actual predictions.

* Set random_state / seed = 42 everywhere so the run is reproducible.
* If you tune a threshold or hyperparameter, tune it on the TRAINING split
  only. Touching the test split during tuning leaks the evaluation set.
* Keep total runtime under 90 seconds. Avoid plain OneClassSVM on the full
  dataset (O(n^2)); use Nystroem + SGDOneClassSVM instead.
* Print progress to stdout; it is captured and shown in the UI.
"""
